# Generated by Django 2.1.4 on 2019-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
    ]
